In [3]:
import sys
sys.dont_write_bytecode = True

import warnings
warnings.filterwarnings("ignore")

import importlib
from src.main.python.schema import model
importlib.reload(model)

ImportError: cannot import name 'config' from 'src.main.python.config' (d:\LLM\API\src\main\python\config.py)

In [ ]:
import torch
torch.split(torch.tensor([[1,2,3], [4,5,6]]), 1, dim=0)

(tensor([[1, 2, 3]]), tensor([[4, 5, 6]]))

In [2]:
from src.main.python.config import config

In [63]:
import uuid
import torch
from transformers import DynamicCache

request = model.Request(input_ids = torch.tensor([i for i in range(128)]).unsqueeze(0),
                        status = model.RequestStatus.PREFILLING,
                        request_id = uuid.uuid4(),
                        kv_cache = DynamicCache()
        ) 
for i in range(8):
    vals = request.get_ids()
    print(vals)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])
tensor([[16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])
tensor([[32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])
tensor([[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])
tensor([[64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])
tensor([[80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]])
tensor([[ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
         110, 111]])
tensor([[112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
         126]])


In [64]:
vals = request.get_ids()
print(vals)

vals = request.get_ids()
print(vals)

tensor([[127]])
tensor([[127]])


In [1]:
!python -B -m unittest src.unittest.python.test_LLMserver

.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
